### ISSUE TITLE
Reflect Prefix in passenger names

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#373]
Prefix is not reflected in passenger names for all air methods.
Prefix should be included as `prefix` attribute.

**Comment by InkFaust** [comment]
Hello @dchertousov 
During the investigation, I've found that actually, names contains the prefix as it supposed to be and this procedure is handling on GDS side, I guess because it comes with response (eg. on getTicket call).

I think the original idea of creating this issue was the problem of one of our test procedure during which we'd have a problem with name compatibilities, I can guess that the booking we're talked about were created with some mistake, also this was the only one that failed (as much as I know).

To proof my words please find my screenshot from this investigation below.

<img width="376" alt="screen shot 2019-03-06 at 4 11 44 pm" src="https://user-images.githubusercontent.com/15357910/53862770-b373e880-402b-11e9-8bbe-a281a8a2d80b.png">

**Comment by dchertousov** [comment]
@InkFaust tried once again running getTickets against PNR: 8XWBTI.

Got response like this (which is not handled properly):

```
        <common_v36_0:BookingTraveler Key="R/2UvieB0BKAJI5oKhAAAA==" TravelerType="ADT" Age="34" DOB="1984-07-04" Gender="M">
          <common_v36_0:BookingTravelerName Prefix="MR" First="FIRSTNAME" Last="LASTNAME"/>
```

(Name is changed)
