### ISSUE TITLE
Serious flaws in implementation

### ISSUE THREAD

**Issue by digital230** [Travelport-Ukraine/uapi-json#487]
Hi, i am in process of getting production credentials  the travelport guy who is reviewing my case send me some 16,19 bugs some of then was minor but some major . in LFS there were minor bugs i managed to solve but in AirPrice there are some complex bugs that i am currently fixing . unfortunately i am not able to share code but i will share issues reported by travelport when i will get credentials.

**Comment by Smotrov** [comment]
Hi @digital230 thank you! Please share your findings in more details. Otherwise, I'm afraid it is not clear what should be done in order to close this ticket. 
If you already have some fixes, [your contribution](https://github.com/Travelport-Ukraine/uapi-json/blob/master/CONTRIBUTING.md) will be highly appreciated.

**Comment by creduo** [comment]
You can share your issues here even before you get the credential. The company's agent cannot be always be a only answer, there are many kind of use cases out there, and not all solutions are same. :)

**Comment by digital230** [comment]
@creduo i was using Uapi Xml when submit for review then agent ask me to do different modifications in uapi xml . 
@Smotrov  unfortunatly i cannot contribute the code i writing is for quick fixes and not up to the mark

**Comment by Smotrov** [comment]
Would appriciate if you'll raise new issues when you'll be ready to describe exact problem in uAPI-JSON. 
So far, I''m closing this one.
