### ISSUE TITLE
Remove manual API version config

### ISSUE THREAD

**Issue by dchertousov** [Travelport-Ukraine/uapi-json#97]
At the time being parser accepts API version, then replaces it if detected version in template.
It's an unclear way, and I propose to replace it. We need to settle situations where we need response without root object and error situations.

**Comment by articice** [comment]
>where we need response without root object 
uAPI sometimes replies with a JSON or server error text and these are checked for before actually parsing XML. Are you talking about them?
For XML there always is a root object.

**Comment by shmuga** [comment]
@articice AFAIK you wrote handler for json errors [here](https://github.com/Travelport-Ukraine/uapi-json/blob/master/src/Request/uapi-request.js#L119)

**Comment by shmuga** [comment]
I think we can leave it for tests. It's more comfortable to have it as a parameter rather than override it in some hacky ways. Example https://github.com/Travelport-Ukraine/uapi-json/pull/122/commits/8d47e469fd8d076d2d0197b25267522e3696b34f#diff-dbd11097de4be6a6bfed089f33f42f75R100

As you see I'm not calling parse directly, but testing error handling function only. So version can't be auto-detected.

Please reopen the issue if disagree only.
